@host = http://localhost:5250
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NmIwODE1Mi05NTg0LTQyYWMtYjFjMi05YjA0ZTI3YjhiOWEiLCJnaXZlbl9uYW1lIjoia2V2aW4iLCJmYW1pbHlfbmFtZSI6Im1hbnphbm8iLCJqdGkiOiIyYjJlNGE3Ny00NjllLTQwNTItYjNiYy1iZmRmYTA0NmUyNjciLCJleHAiOjE3MTA3NzMyMzcsImlzcyI6IkNpbmVtYXgiLCJhdWQiOiJDaW5lbWF4In0.5Z03bGEJ9xmAQat46-ahq0Hq8xE-VFnl4yqVv5M7smo
@seatid = f35ab2bf-7e87-4635-ad09-069be8f378b0
@userid = 23d72268-0102-4d02-8608-6caea4641184
@projectionid = 852b30e5-8e42-4747-b28e-a50a6bd1969c
@paymentType = c941b33c-4099-44a2-9272-7a86f379fa8e
POST {{host}}/tickets/confirm/{{paymentType}}
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "ConfirmTicketsRequests" : [
        {
            "seatid" : "{{seatid}}",
            "userid" : "{{userid}}",
            "projectionid" : "{{projectionid}}"
        }
    ]
}