@host = http://localhost:5250
@id = 2e0f20fa-7bf9-4362-bbbd-160859952b7e
POST  {{host}}/tickets/refund/{{id}}
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "id" : "{{id}}"
}
