@host = http://localhost:5250
@startDate = 2019-01-01
@endDate = 2099-01-31
@limit = "10"
GET  {{host}}/tickets/roomCounts/2010-01-01/2099-01-31/10
Content-Type: application/json
//Authorization: Bearer {{token}}

{

}
