@host = http://localhost:5250
//@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJDaW5lbWF4LkRvbWFpbi5Vc2VyLlZhbHVlT2JqZWN0cy5Vc2VySWQiLCJnaXZlbl9uYW1lIjoia2V2aW4iLCJmYW1pbHlfbmFtZSI6Im1hbnphbm8iLCJqdGkiOiI1NWNmZmZmNC1iM2VkLTQyNzMtOWYxMy1lMjQ3MDFkNDcxN2YiLCJleHAiOjE3MTE1MTgxODIsImlzcyI6IkNpbmVtYXgiLCJhdWQiOiJDaW5lbWF4In0.1Y--W8wMMLNhjz2s1C92VFEcDIHCGjNhj1hnJPJQ7bQ
POST {{host}}/actors
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "firstname":"Maria",
    "lastname":"Carey"
}
