@host = http://localhost:5250
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYWE2YjAwZC1lNmJmLTRjNmMtODgwNy02NGEwYjI4ZTEyOWEiLCJnaXZlbl9uYW1lIjoiYXNkYXNkYXNkYSIsImZhbWlseV9uYW1lIjoiQVNEQVNEQSIsImp0aSI6IjJkNDUwNjlkLTMzYTQtNDFlNS05ODhlLWVmNGY3MzllODE1NSIsImJpcnRoZGF0ZSI6IjYvMTAvMjAwMiIsImVtYWlsIjoiYXNkYXNkYXNkYXMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBRE1JTiIsImV4cCI6MTcxMTk0NDU0OSwiaXNzIjoiQ2luZW1heCIsImF1ZCI6IkNpbmVtYXgifQ.RKwGEurV74X3Gu8hIXH381hvNon7CUDfmBx4VvdgLwY
POST {{host}}/actors
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstname":"ss",
    "lastname":"Casdaguama"
}
