@host = http://localhost:5250
@actorId = e6b32a61-92f0-4077-b393-6513b9bd855b

PATCH {{host}}/actors/{{actorId}}
Content-Type: application/json-patch+json

[
    {
        "op": "replace",
        "path": "/FirstName",
        "value": "Maria"
    },
    {
        "op": "replace",
        "path": "/LastName",
        "value": "santos"
    }
]