@host = http://localhost:5250
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NmIwODE1Mi05NTg0LTQyYWMtYjFjMi05YjA0ZTI3YjhiOWEiLCJnaXZlbl9uYW1lIjoia2V2aW4iLCJmYW1pbHlfbmFtZSI6Im1hbnphbm8iLCJqdGkiOiIyYjJlNGE3Ny00NjllLTQwNTItYjNiYy1iZmRmYTA0NmUyNjciLCJleHAiOjE3MTA3NzMyMzcsImlzcyI6IkNpbmVtYXgiLCJhdWQiOiJDaW5lbWF4In0.5Z03bGEJ9xmAQat46-ahq0Hq8xE-VFnl4yqVv5M7smo
POST {{host}}/projections
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "movie": "1d39f457-68f1-49fa-a6be-e396d771720a",
    "room": "18464df8-eb1a-4ea4-971f-1c8f8d92f42e",
    "date": "2022-05-11T00:00:00",
    "price": "20"
}
