@host = http://localhost:5250
@id = f8110626-ec13-466d-8104-bb322f380544
DELETE  {{host}}/projections/{{id}}
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "projectionid" : "{{id}}"
}
