@host = http://localhost:5250
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZWNlOWY3OC01YzY4LTQ0YzEtOWM4MC02MGZlZGU0MTk2NTQiLCJnaXZlbl9uYW1lIjoiSmFja3NvbiIsImZhbWlseV9uYW1lIjoiVmVyYSIsImp0aSI6IjljMmIwYzkwLTg0Y2UtNGY5Ny1iMjQyLTBhNzIzYjlkOTE2NSIsImJpcnRoZGF0ZSI6IjYvMTAvMjAwMiIsImVtYWlsIjoiSkNAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQURNSU4iLCJleHAiOjE3MTM5MDkxMTAsImlzcyI6IkNpbmVtYXgiLCJhdWQiOiJDaW5lbWF4In0.bWZVslEmLOTKeGzpvkgdIJNwmUguKxMc1XpE2rIbxYU
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

