@host = http://localhost:5250

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "kevin",
    "lastName": "manzano",
    "email": "kevin@gmail.com",
    "password": "kevin1234!"
}
