@host = http://localhost:5250

POST {{host}}/users
Content-Type: application/json

{
    "firstname" : "Roger", 
    "lastname":"Vera",
    "email":"roger123@gmail.com",
    "password":"123123asd",
    "birthday": "2002-06-10",
    "role":"USER"
}
