@host = http://localhost:5250
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJDaW5lbWF4LkRvbWFpbi5Vc2VyLlZhbHVlT2JqZWN0cy5Vc2VySWQiLCJnaXZlbl9uYW1lIjoia2V2aW4iLCJmYW1pbHlfbmFtZSI6Im1hbnphbm8iLCJqdGkiOiJmNWI5M2ViMC05Mjg4LTRhNzktYjkyOS00M2Y2YjI0M2Q4YzQiLCJleHAiOjE3MTE2OTY4NDcsImlzcyI6IkNpbmVtYXgiLCJhdWQiOiJDaW5lbWF4In0.zatxxbZE67xb-_KR2RW94N6-RnFn_rR8Ad4kAKSN1PU

POST {{host}}/movies
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "Name":"Mi peli 8",
    "Description":"Best peli",
    "Duration":"02:30:00",
    "Premiere":"2020-04-01T00:00:00",
    "IconURL":"https://ejemplo.com/icon.png",
    "TrailerURL":"https://ejemplo.com/trailer.mp4",
    "Actors":["4021062c-e295-4531-9fab-2c74873cd682","24847ff4-3ccd-4536-9695-9985df03acfc"],
    "Countries":["0fd4f031-5940-49cc-9326-43671a8a7bfa","d64c559e-4dd8-4645-a19f-f9c34b005762"],
    "Directors":["ebcc3605-e955-4142-8ab0-9d8eb47186c7","75a29fc8-d6d4-46e4-bcef-71a82784e486"],   
    "Genres":["bb6f6ec0-6389-41bf-9b68-679ae1a8ef8f","0091e0fb-9e03-4a68-9fb6-7e9bcc2b1311"]
    
}
