@host = http://localhost:5250
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJDaW5lbWF4LkRvbWFpbi5Vc2VyLlZhbHVlT2JqZWN0cy5Vc2VySWQiLCJnaXZlbl9uYW1lIjoia2V2aW4iLCJmYW1pbHlfbmFtZSI6Im1hbnphbm8iLCJqdGkiOiJmNWI5M2ViMC05Mjg4LTRhNzktYjkyOS00M2Y2YjI0M2Q4YzQiLCJleHAiOjE3MTE2OTY4NDcsImlzcyI6IkNpbmVtYXgiLCJhdWQiOiJDaW5lbWF4In0.zatxxbZE67xb-_KR2RW94N6-RnFn_rR8Ad4kAKSN1PU

POST {{host}}/movies
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "Name":"Mi peli",
    "Description":"Best peli",
    "Duration":"02:30:00",
    "Premiere":"2020-04-01T00:00:00",
    "IconURL":"https://ejemplo.com/icon.png",
    "TrailerURL":"https://ejemplo.com/trailer.mp4",
    "Actors":["abc6ea68-af72-4c3f-add1-72883d271496"],
    "Countries":["96b07805-e238-4757-9c3e-962c78921ba4"],
    "Directors":["d19182d6-87f5-4149-9c41-03b3bc7806a6"],   
    "Genres":["0ff58171-acd1-43d3-ab96-8b077c410ffe"]
    
}
