@host = http://localhost:5250
@movieId = 096aac4a-410c-4d7e-a02d-38575dc13d4d

PATCH {{host}}/movies/{{movieId}}
Content-Type: application/json-patch+json

[
    {
        "op": "remove",
        "path": "/genres",
        "value": "8b63cd03-e037-492c-ae1a-4443353764c9"
    },
    {
        "op": "add",
        "path": "/genres",
        "value": "2ceadd7d-cf50-4969-b542-d04b177553a8"
    }
]